### ISSUE TITLE
Nice Demo and Repo

### ISSUE THREAD

**Issue by Jaikant** [jbaxleyiii/basic-up-engine-example#4]
Hey, 
This is really nice!
I just want to check, is it possible to completely remove AWS fargate from the picture. 
I would just like to run the graphQL service from lambda and possibly API gateway?
With graphql using dynamoDB for storage?

Thanks!

**Comment by stubailo** [comment]
Hi! That's not really the purpose of the repo, but it is possible to run GraphQL in that way!
